---------------------------------------------
--         Cars                            --
---------------------------------------------
PAC_E = {}
PAC_E.BlacklistedVehicles = {
	{name = "cargoplane", ban = true , log = true},
	{name = "cerberus",   ban = true , log = true},
	{name = "cerberus2",  ban = true , log = true},
	{name = "tug", ban = true, log = true},
	{name = "cerberus3",  ban = true , log = true},
	{name = "hauler2",    ban = true , log = true},
	{name = "phantom2",   ban = true , log = true},
	{name = "terbyte",    ban = true , log = true},
	{name = "issi4",      ban = true , log = true},
	{name = "issi5",      ban = true , log = true},
	{name = "issi6",      ban = true , log = true},
	{name = "akula",      ban = true , log = true},
	{name = "annihilator",ban = true , log = true},
	{name = "buzzard",    ban = true , log = true},
	{name = "hunter",     ban = true , log = true},
	{name = "savage",     ban = true , log = true},
	{name = "apc",        ban = true , log = true},
	{name = "barrage",    ban = true , log = true},
	{name = "chernobog",  ban = true , log = true},
	{name = "halftVCACk", ban = true , log = true},
	{name = "khanjali",   ban = true , log = true},
	{name = "minitank",   ban = true , log = true},
	{name = "rhino",      ban = true , log = true},
	{name = "scarab",     ban = true , log = true},
	{name = "scarab2",    ban = true , log = true},
	{name = "scarab3",    ban = true , log = true},
	{name = "thruster",   ban = true , log = true},
	{name = "trailersmall2",ban = true , log = true},
	{name = "oppressor",  ban = true , log = true},
  	{name = "dump",       ban = true , log = true},
	{name = "oppressor2", ban = true , log = true},
	{name = "dominator4", ban = true , log = true},
	{name = "dominator5", ban = true , log = true},
 	{name = "riot",       ban = true , log = true},
	{name = "dominator6", ban = true , log = true},
	{name = "dukes2",     ban = true , log = true},
	{name = "impaler2",   ban = true , log = true},
	{name = "impaler3",   ban = true , log = true},
	{name = "impaler4",   ban = true , log = true},
	{name = "imperator",  ban = true , log = true},
	{name = "imperator2", ban = true , log = true},
	{name = "imperator3", ban = true , log = true},
	{name = "bruiser",    ban = true , log = true},
	{name = "bruiser2",   ban = true , log = true},
	{name = "bruiser3",   ban = true , log = true},
	{name = "brutus",     ban = true , log = true},
	{name = "brutus2",    ban = true , log = true},
	{name = "brutus3",    ban = true , log = true},
	{name = "caVCACara",  ban = true , log = true},
	{name = "dune4",      ban = true , log = true},
	{name = "dune5",      ban = true , log = true},
	{name = "insurgent",  ban = true , log = true},
	{name = "insurgent3", ban = true , log = true},
	{name = "menacer",    ban = true , log = true},
	{name = "nightshark", ban = true , log = true},
	{name = "technical",  ban = true , log = true},
	{name = "technical2", ban = true , log = true},
	{name = "technical3", ban = true , log = true},
  	{name = "tug",        ban = true , log = true},
	{name = "zhaba",      ban = true , log = true},
	{name = "avenger",    ban = true , log = true},
	{name = "avenger2",   ban = true , log = true},
	{name = "besra",      ban = false , log = false},
	{name = "jet",        ban = true , log = true},
	{name = "hydra",      ban = true , log = true},
	{name = "strikeforce",ban = true , log = true},
	{name = "titan",      ban = true , log = false},
	{name = "volatol",    ban = true ,  log = true},
	{name = "limo2",      ban = true ,  log = true},
	{name = "zr380",      ban = true ,  log = true},
	{name = "zr3802",     ban = true ,  log = true},
	{name = "zr3803",     ban = true ,  log = true},
	{name = "deluxo",     ban = true ,  log = true},
  	{name = "luxor",      ban = true ,  log = true},
	{name = "vigilante",  ban = true ,  log = true},
	{name = "boxville5",  ban = true ,  log = true},
	{name = "kuruma2",    ban = true ,  log = true},
	{name = "scramjet",   ban = true ,  log = true},
	{name = "boat",       ban = true ,  log = true},
}

---------------------------------------------
--         Models                          --
---------------------------------------------
PAC_E.ObjectBan = {
  ["-930879665"] = true,
  ["658306424"] = true,
  ["3821613641"] = true,
  ["841438406"] = true,
  ["566160949"] = true,
  ["3295673357"] = true,
  ["-1072941776"] = true,
  ["452618762"] = true,
  ["-1268267712"] = true,
  ["1952396163"] = true,
  ["206865238"] = true,
  ["1328154590"] = true,
  ["803874239"] = true,
  ["-473036318"] = true,
  ["-145066854"] = true,
  ["-82704061"] = true,
  ["1338692320"] = true,
  ["-1404196790"] = true,
  ["2890770506"] = true,
  ["-629735826"] = true,
  ["-759902142"] = true,
  ["1978613345"] = true,
  ["1765283457"] = true,
  ["1399999408"] = true,
  ["-1363788725"] = true,
  ["-968169310"] = true,
  ["-1885111468"] = true,
  ["4121918930"] = true,
  [GetHashKey("csx_seabed_rock3_")] = true,
  ["1121747524"] = true,
  ["-1474974664"] = true,
  ["-1404869155"] = true,
  ["-1604099433"] = true,
  [GetHashKey("ar_prop_ar_arrow_wide_xl")] = true,
  [GetHashKey("cs4_lod_04_slod2")] = true,
  [GetHashKey("po1_lod_slod4")] = true,
  [GetHashKey("id2_lod_slod4")] = true,
  [GetHashKey("ap1_lod_slod4")] = true,
  [GetHashKey("prop_tv_03")] = true,
  [GetHashKey("prop_alien_egg_01")] = true,
  [GetHashKey("prop_xmas_tree_int")] = true,
  [GetHashKey("sm_lod_slod2_22")] = true,
  [GetHashKey("dt1_lod_slod3")] = true,
  [GetHashKey("prop_jetski_ramp_01")] = true,
  [GetHashKey("prop_juicestand")] = true,
  ["-1147467348"] = true,
  ["-1156020871"] = true,
  ["-422877666"] = true,
  ["-1118757580"] = true,
  ["2967811882"] = true,
  ["3957771795"] = true,
  ["4185368029"] = true,
}

PAC_E.ModelWhitelist = {
	["0"] = true,
  ["1760825203"] = true,
  ["1564805541"] = true,
  ["1299409410"] = true,
  ["75487256"] = true,
  ["-746954904"] = true,
  ["-511116411"] = true,
  ["413312110"] = true,
  [GetHashKey("prop_roadcone02a")] = true,
  [GetHashKey("prop_mp_cone_04")] = true,
  [GetHashKey("prop_barrier_work05")] = true,
  [GetHashKey("Prop_MP_Arrow_Barrier_01")] = true
}

---------------------------------------------
--         Peds                            --
---------------------------------------------
PAC_E.PedBlacklist = {
  "a_m_m_genfat_01",
  "a_m_m_eastsa_01",
  "a_m_o_acult_01",
  "a_m_m_afriamer_01",
  "a_m_m_indian_01",
  "u_m_y_babyd",
  "csb_stripper_01",
  "csb_mweather"
}

---------------------------------------------
--         Explosions                      --
---------------------------------------------
PAC_E.Explosions = {
  [0] = { name = "Grenade", log = true, ban = false},
  [1] = { name = "Grenade Launcher", log = true, ban = true},
  [2] = { name = "Sticky Bomb", log = true, ban = true},
  [3] = { name = "Molotov", log = true, ban = true},
  [4] = { name = "Rocket", log = true, ban = true},
  [5] = { name = "TankShell", log = true, ban = true},
  [6] = { name = "Hi_Octane", log = true, ban = true},
  [7] = { name = "Car", log = true, ban = false},
  [8] = { name = "Plane", log = true, ban = false},
  [9] = { name = "PetrolPump", log = true, ban = false},
  [10] = { name = "Bike", log = true, ban = false},
  [11] = { name = "Dir_Steam", log = false, ban = false},
  [12] = { name = "Dir_Flame", log = false, ban = false},
  [13] = { name = "Dir_Water_Hydrant", log = false, ban = false},
  [14] = { name = "Dir_Gas_Canister", log = false, ban = false},
  [15] = { name = "Boat", log = true, ban = true},
  [16] = { name = "Ship_Destroy", log = true, ban = true},
  [17] = { name = "Truck", log = true, ban = false},
  [18] = { name = "Bullet", log = true, ban = true},
  [19] = { name = "SmokeGrenadeLauncher", log = true, ban = true},
  [20] = { name = "SmokeGrenade", log = true, ban = true},
  [21] = { name = "BZGAS", log = true, ban = true},
  [22] = { name = "Flare", log = true, ban = true},
  [23] = { name = "Gas_Canister", log = true, ban = false},
  [24] = { name = "Extinguisher", log = true, ban = true},
  [25] = { name = "Programmablear",log = true, ban = true},
  [26] = { name = "Train", log = true, ban = true},
  [27] = { name = "Barrel", log = true, ban = true},
  [28] = { name = "PROPANE", log = true, ban = true},
  [29] = { name = "Blimp", log = true, ban = true},
  [30] = { name = "Dir_Flame_Explode", log = true, ban = false},
  [31] = { name = "Tanker", log = true, ban = false},
  [32] = { name = "PlaneRocket", log = true, ban = true},
  [33] = { name = "VehicleBullet", log = true, ban = true},
  [34] = { name = "Gas_Tank", log = true, ban = false},
  [35] = { name = "EXP_TAG_BIRD_CRAP", log = true, ban = true},
  [36] = { name = "EXP_TAG_RAILGUN", log = true, ban = true},
  [37] = { name = "EXP_TAG_BLIMP2", log = true, ban = true},
  [38] = { name = "EXP_TAG_FIREWORK", log = true, ban = true},
  [39] = { name = "EXP_TAG_SNOWBALL", log = true, ban = true},
  [40] = { name = "EXP_TAG_PROXMINE", log = true, ban = true},
  [41] = { name = "EXP_TAG_VALKYRIE_CANNON", log = true, ban = true},
  [42] = { name = "EXP_TAG_AIR_DEFENCE", log = true, ban = true},
  [43] = { name = "EXP_TAG_PIPEBOMB", log = true, ban = true},
  [44] = { name = "EXP_TAG_VEHICLEMINE", log = true, ban = true},
  [45] = { name = "EXP_TAG_EXPLOSIVEAMMO", log = true, ban = true},
  [46] = { name = "EXP_TAG_APCSHELL", log = true, ban = true},
  [47] = { name = "EXP_TAG_BOMB_CLUSTER", log = true, ban = true},
  [48] = { name = "EXP_TAG_BOMB_GAS", log = true, ban = true},
  [49] = { name = "EXP_TAG_BOMB_INCENDIARY", log = true, ban = true},
  [50] = { name = "EXP_TAG_BOMB_STANDARD", log = true, ban = true},
  [51] = { name = "EXP_TAG_TORPEDO", log = true, ban = true},
  [52] = { name = "EXP_TAG_TORPEDO_UNDERWATER", log = true, ban = true},
  [53] = { name = "EXP_TAG_BOMBUSHKA_CANNON", log = true, ban = true},
  [54] = { name = "EXP_TAG_BOMB_CLUSTER_SECONDARY", log = true, ban = true},
  [55] = { name = "EXP_TAG_HUNTER_BARRAGE", log = true, ban = true},
  [56] = { name = "EXP_TAG_HUNTER_CANNON", log = true, ban = true},
  [57] = { name = "EXP_TAG_ROGUE_CANNON", log = true, ban = true},
  [58] = { name = "EXP_TAG_MINE_UNDERWATER", log = true, ban = true},
  [59] = { name = "EXP_TAG_ORBITAL_CANNON", log = true, ban = true},
  [60] = { name = "EXP_TAG_BOMB_STANDARD_WIDE", log = true, ban = true},
  [61] = { name = "EXP_TAG_EXPLOSIVEAMMO_SHOTGUN", log = true, ban = true},
  [62] = { name = "EXP_TAG_OPPRESSOR2_CANNON", log = true, ban = true},
  [63] = { name = "EXP_TAG_MORTAR_KINETIC", log = true, ban = true},
  [64] = { name = "EXP_TAG_VEHICLEMINE_KINETIC", log = true, ban = true},
  [65] = { name = "EXP_TAG_VEHICLEMINE_EMP", log = true, ban = true},
  [66] = { name = "EXP_TAG_VEHICLEMINE_SPIKE", log = true, ban = true},
  [67] = { name = "EXP_TAG_VEHICLEMINE_SLICK", log = true, ban = true},
  [68] = { name = "EXP_TAG_VEHICLEMINE_TAR", log = true, ban = true},
  [69] = { name = "EXP_TAG_SCRIPT_DRONE", log = true, ban = true},
  [70] = { name = "EXP_TAG_RAYGUN", log = true, ban = true},
  [71] = { name = "EXP_TAG_BURIEDMINE", log = true, ban = true},
  [72] = { name = "EXP_TAG_SCRIPT_MISSILE", log = true, ban = true},
  [73] = { name = "EXP_TAG_RCTANK_ROCKET", log = true, ban = true},
  [74] = { name = "EXP_TAG_BOMB_WATER", log = true, ban = true},
  [75] = { name = "EXP_TAG_BOMB_WATER_SECONDARY", log = true, ban = true},
  [76] = { name = "_0xF728C4A9", log = true, ban = true},
  [77] = { name = "_0xBAEC056F", log = true, ban = true},
  [78] = { name = "EXP_TAG_FLASHGRENADE", log = true, ban = true},
  [79] = { name = "EXP_TAG_STUNGRENADE", log = true, ban = true},
  [80] = { name = "_0x763D3B3B", log = true, ban = true},
  [81] = { name = "EXP_TAG_SCRIPT_MISSILE_LARGE", log = true, ban = true},
  [82] = { name = "EXP_TAG_SUBMARINE_BIG", log = true, ban = true},
}

---------------------------------------------
--         Particles                       --
---------------------------------------------
PAC_E.WhitelistedParticles = {
  'scr_indep_firework_starburst',
  'scr_indep_firework_shotburst',
  'scr_indep_firework_fountain',
  'scr_indep_firework_trailburst',
  'scr_firework_xmas_ring_burst_rgw',
  'scr_firework_xmas_burst_rgw',
  'scr_firework_xmas_repeat_burst_rgw',
  'scr_firework_xmas_spiral_burst_rgw',
  'scr_xmas_firework_sparkle_spawn',
  'scr_indep_firework_sparkle_spawn',
  'scr_indep_firework_trailburst_spawn',
  'scr_indep_firework_burst_spawn',
  'scr_indep_firework_trail_spawn',
  'scr_indep_firework_grd_burst',
  'scr_indep_launcher_sparkle_spawn',
  'scr_indep_firework_air_burst',
  'proj_indep_flare_trail',
  'scr_firework_indep_burst_rwb',
  'scr_firework_indep_spiral_burst_rwb',
  'scr_firework_indep_ring_burst_rwb',
  'scr_xmas_firework_burst_fizzle',
  'scr_firework_indep_repeat_burst_rwb',
  'veh_backfire',
  'veh_respray_smoke'
}